# Page_1_Cdbd Page Locators
class Page1CdbdLocators:
     = "page.locator('span')"
    558_357 = "page.locator('span')"
    BTN_LOGIN = "page.locator('button.login-button')"
    DONT_HAVE_AN_ACCOUNT = "page.locator('div.signup-link')"
    EMAIL = "page.locator('div.form-group')"
    EMAIL_PASSWORD_FORGOT_PASS = "page.locator('div.form-wrapper')"
    EMAIL_PASSWORD_FORGOT_PASS_473_270 = "page.locator('form.login-form')"
    FORGOT_PASSWORD = "page.locator('div.form-footer')"
    HEADING_WELCOME_BACK = "page.locator('h2.welcome-text')"
    INPUT_EMAIL_483_296 = "page.locator('#login-email')"
    LINK_FORGOT_PASSWORD_696_449 = "page.locator('a.forgot-link')"
    LINK_SIGN_UP_HERE_592_685 = "page.locator('a')"
    OR = "page.locator('div.or-text')"
    PASSWORD = "page.locator('div.form-group')"
    SIGN_UP_HERE = "page.locator('span.signup-highlight')"
    WELCOME_BACKEMAIL_PASSWORD = "page.locator('html')"
    WELCOME_BACKEMAIL_PASSWORD_0_0 = "page.locator('body')"
